import Icon from "./Icon";
import { ReactComponent as AddressBook } from "./svgs/AddressBook.svg";
import { ReactComponent as AppWindow } from "./svgs/AppWindow.svg";
import { ReactComponent as Archive } from "./svgs/Archive.svg";
import { ReactComponent as ArchiveBox } from "./svgs/ArchiveBox.svg";
import { ReactComponent as Bell } from "./svgs/Bell.svg";
import { ReactComponent as Home } from "./svgs/Home.svg";
import { ReactComponent as JournalBookmark } from "./svgs/JournalBookmark.svg";
import { ReactComponent as PlusCircleFill } from "./svgs/PlusCircleFill.svg";
import { ReactComponent as Search } from "./svgs/Search.svg";
import { ReactComponent as Plus } from "./svgs/Plus.svg";
import { ReactComponent as PlusBlue } from "./svgs/PlusBlue.svg";
import { ReactComponent as Download } from "./svgs/Download.svg";
import { ReactComponent as ChevronLeft } from "./svgs/ChevronLeft.svg";
import { ReactComponent as ThreeDotsVertical } from "./svgs/ThreeDotsVertical.svg";
import { ReactComponent as Calendar } from "./svgs/Calendar.svg";
import { ReactComponent as PlusCircleDotted } from "./svgs/PlusCircleDotted.svg";
import { ReactComponent as FolderCheck } from "./svgs/FolderCheck.svg";
import { ReactComponent as Wallet } from "./svgs/Wallet.svg";
import { ReactComponent as FolderPlus } from "./svgs/FolderPlus.svg";
import { ReactComponent as ChatRightText } from "./svgs/ChatRightText.svg";
import { ReactComponent as PersonPlus } from "./svgs/PersonPlus.svg";
import { ReactComponent as HandThumbsUp } from "./svgs/HandThumbsUp.svg";
import { ReactComponent as PencilSquare } from "./svgs/PencilSquare.svg";
import { ReactComponent as Upload } from "./svgs/Upload.svg";
import { ReactComponent as Volunteers } from "./svgs/Volunteers.svg";
import { ReactComponent as Partners } from "./svgs/Partners.svg";
import { ReactComponent as BoxArrowInUpRight } from "./svgs/BoxArrowInUpRight.svg";
import { ReactComponent as EditSquare } from "./svgs/EditSquare.svg";
import { ReactComponent as CheckLg } from "./svgs/CheckLg.svg";
import { ReactComponent as CashCoin } from "./svgs/CashCoin.svg";
import { ReactComponent as ArrowUpCircleFill } from "./svgs/ArrowUpCircleFill.svg";
import { ReactComponent as ArrowDownCircleFill } from "./svgs/ArrowDownCircleFill.svg";
import { ReactComponent as CaretDown } from "./svgs/CaretDown.svg";
import { ReactComponent as ArrowClose } from "./svgs/ArrowClose.svg";
import { ReactComponent as GraphUpArrow } from "./svgs/GraphUpArrow.svg";
import { ReactComponent as ChalkboardTeacherDuotone } from "./svgs/ChalkboardTeacherDuotone.svg";
import { ReactComponent as ChalkboardDuotone } from "./svgs/ChalkboardDuotone.svg";
import { ReactComponent as ArrowDownGreen } from "./svgs/ArrowDownGreen.svg";
import { ReactComponent as ArrowDownYellow } from "./svgs/ArrowDownYellow.svg";
import { ReactComponent as ArrowDownRed } from "./svgs/ArrowDownRed.svg";
import { ReactComponent as EllipseGreen } from "./svgs/EllipseGreen.svg";
import { ReactComponent as EllipseRed } from "./svgs/EllipseRed.svg";
import { ReactComponent as EllipseYellow } from "./svgs/EllipseYellow.svg";
import { ReactComponent as ExclamationCircleFill } from "./svgs/ExclamationCircleFill.svg";
import { ReactComponent as ArrowUpGreen } from "./svgs/ArrowUpGreen.svg";
import { ReactComponent as ArrowDowmRed } from "./svgs/ArrowDowmRed.svg";
import { ReactComponent as ArrowClockwise } from "./svgs/ArrowClockwise.svg";
import { ReactComponent as XCircle } from "./svgs/XCircle.svg";

Icon.AddressBook = AddressBook;
Icon.AppWindow = AppWindow;
Icon.Archive = Archive;
Icon.ArchiveBox = ArchiveBox;
Icon.Bell = Bell;
Icon.Home = Home;
Icon.JournalBookmark = JournalBookmark;
Icon.PlusCircleFill = PlusCircleFill;
Icon.Search = Search;
Icon.Plus = Plus;
Icon.PlusBlue = PlusBlue;
Icon.Download = Download;
Icon.ChevronLeft = ChevronLeft;
Icon.ThreeDotsVertical = ThreeDotsVertical;
Icon.Calendar = Calendar;
Icon.PlusCircleDotted = PlusCircleDotted;
Icon.FolderCheck = FolderCheck;
Icon.Wallet = Wallet;
Icon.FolderPlus = FolderPlus;
Icon.ChatRightText = ChatRightText;
Icon.PersonPlus = PersonPlus;
Icon.FolderCheck = FolderCheck;
Icon.HandThumbsUp = HandThumbsUp;
Icon.PencilSquare = PencilSquare;
Icon.Upload = Upload;
Icon.Volunteers = Volunteers;
Icon.Partners = Partners;
Icon.BoxArrowInUpRight = BoxArrowInUpRight;
Icon.EditSquare = EditSquare;
Icon.CheckLg = CheckLg;
Icon.CashCoin = CashCoin;
Icon.ArrowUpCircleFill = ArrowUpCircleFill;
Icon.ArrowDownCircleFill = ArrowDownCircleFill;
Icon.CaretDown = CaretDown;
Icon.ArrowClose = ArrowClose;
Icon.GraphUpArrow = GraphUpArrow;
Icon.ChalkboardDuotone = ChalkboardDuotone;
Icon.ChalkboardTeacherDuotone = ChalkboardTeacherDuotone;
Icon.ArrowDownGreen = ArrowDownGreen;
Icon.ArrowDownRed = ArrowDownRed;
Icon.ArrowDownYellow = ArrowDownYellow;
Icon.EllipseGreen = EllipseGreen;
Icon.EllipseRed = EllipseRed;
Icon.EllipseYellow = EllipseYellow;
Icon.ExclamationCircleFill = ExclamationCircleFill;
Icon.ArrowUpGreen = ArrowUpGreen;
Icon.ArrowDowmRed = ArrowDowmRed;
Icon.ArrowClockwise = ArrowClockwise;
Icon.XCircle = XCircle;

export default Icon;
